import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/*",
		"@lezer/*",
		...builtinModules
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	// svguitar picks its renderer at runtime: if `process.versions.node` is set
	// it renders through svgdom (its server-side path) instead of the browser
	// DOM, and the returned object is not a real SVG.js Svg — `.viewbox()` is
	// missing and every diagram throws. Obsidian's desktop app is Electron with
	// Node integration, so that check is true there and diagrams break, while
	// mobile (WKWebView, no `process`) works. This bundle only ever runs in a
	// webview, so pin the check to false and keep the browser renderer.
	define: { "process.versions.node": "undefined" },
	outfile: "main.js",
	minify: prod
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
